#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         1
bspc config window_gap          5
bspc config focused_border_color   "#f9f5d7"   # focused window
bspc config normal_border_color   "#928374"   # unfocused window
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
export PATH=/usr/local/bin:$PATH
export XDG_DATA_DIRS="/var/lib/flatpak/exports/share:/home/void/.local/share/flatpak/exports/share:/usr/local/share:/usr/share" &
picom &
polybar &
feh --bg-fill ouchy.png &
nvidia-settings --load-config-only &
